export const bochkSelectors = {
  startBooking: [
    "li:has-text('預約開立香港賬戶') a.morelink",
    "a.morelink[href*='hkpaccountopen']",
    "a[href*='hkpaccountopen']",
    "text=預約開立香港賬戶"
  ],
  district: "select[name*='district'], select[id*='district']",
  branch: "select[name*='branch'], select[id*='branch']",
  date: "select[name*='date'], select[id*='date']",
  time: "select[name*='time'], select[id*='time']",
  salutation: "input[type='radio'][name*='title'], input[type='radio'][name*='salutation']",
  surname: "input[name*='surname'], input[id*='surname'], input[name*='last'], input[id*='last']",
  givenName: "input[name*='given'], input[id*='given'], input[name*='first'], input[id*='first']",
  countryCode: "select[name*='country'], select[id*='country'], select[name*='area'], select[id*='area']",
  documentType: "#eAAOForm_idType_field, select[name*='document'], select[id*='document'], select[name*='idType'], select[id*='idType']",
  accountType: "#eAAOForm_serviceAccountType_field, select[name*='account'], select[id*='account']",
  phone: "input[name*='phone'], input[id*='phone'], input[name*='mobile'], input[id*='mobile'], input[type='tel']",
  email: "input[name*='email'], input[id*='email'], input[type='email']",
  acceptTerms: "#mortgageLoans_form_acceptTerms_field, input[name='acceptTerms']",
  submit: "#eAAOForm_submit_button, button[type='submit'], input[type='submit'], button:has-text('提交'), button:has-text('確認'), button:has-text('繼續')",
  captcha: [
    "iframe[src*='captcha' i]",
    "iframe[src*='verify' i]",
    "iframe[src*='challenge' i]",
    "[id*='captcha' i]",
    "[class*='captcha' i]",
    "[name*='captcha' i]",
    "[id*='verify' i]",
    "[class*='verify' i]",
    "[name*='verify' i]",
    "[id*='verification' i]",
    "[class*='verification' i]",
    "[name*='verification' i]",
    "[id*='challenge' i]",
    "[class*='challenge' i]",
    "[name*='challenge' i]",
    "input[id*='code' i]",
    "input[name*='code' i]",
    "input[placeholder*='验证码' i]",
    "input[placeholder*='驗證碼' i]",
    "img[src*='captcha' i]",
    "img[id*='captcha' i]",
    "img[class*='captcha' i]",
    "#captcha_img",
    "#captcha"
  ].join(","),
  confirmation: ["text=預約成功", "text=预约成功", "text=確認", "text=成功"]
} as const;
